# Generated by Django 4.2.4 on 2023-08-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image1', models.ImageField(null=True, upload_to='product_images/')),
                ('image3', models.ImageField(null=True, upload_to='product_images/')),
                ('image4', models.ImageField(null=True, upload_to='product_images/')),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('new_arrival', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chipworld.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chipworld.product')),
                ('resolution', models.CharField(max_length=50)),
                ('nightvision', models.CharField(max_length=50)),
                ('fov', models.CharField(max_length=50)),
                ('connectivity', models.CharField(max_length=50)),
            ],
            bases=('chipworld.product',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chipworld.product')),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
            ],
            bases=('chipworld.product',),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chipworld.product')),
                ('print_type', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('connectivity', models.CharField(max_length=50)),
                ('paper_handling', models.CharField(max_length=50)),
            ],
            bases=('chipworld.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chipworld.producttype'),
        ),
    ]
